version: "2"

services:
    api:
        build: ./backend
        
        depends_on:  
            - mongo
        environment:
            - PORT=5000
            - MONGODB_CNN=mongodb://localhost:27017/test
        
    frontend:
        build: ./frontend
        
        ports:
            - "4000:4000"
            
    microservices:
        build: ./microservices

        depends_on:  
            - mongo
        environment:
            - PORT=3000
            - MONGODB_CNN=mongodb://localhost:27017/test 
        
        
    nginx:
        image: nginx:latest
        ports:
            - "8080:8080"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - api
            - frontend
            - microservices
            
    mongo:
        image: mongo
        ports: 
            - "27017:27017"
        
            

    

